// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'models/member.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 658255296345367868),
      name: 'Member',
      lastPropertyId: const obx_int.IdUid(19, 4339754572732378508),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5659995356892222369),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8846676537573119614),
            name: 'dataTime',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5175693972718858319),
            name: 'number',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6964318077685775740),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4589279197445247119),
            name: 'kana3',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6308664108243583555),
            name: 'blanch',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2356490733601697843),
            name: 'rank',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 919148478547667034),
            name: 'sex',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 728448588195070265),
            name: 'age',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4629124996623523366),
            name: 'height',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 7616541928478159120),
            name: 'weight',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 4842146869039647723),
            name: 'blood',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 5311703694034200539),
            name: 'winPointRate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 5563685019089933465),
            name: 'winRate12',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 7386000984543084385),
            name: 'rankPast1',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 3206822075286530144),
            name: 'rankPast2',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 6502025565454242714),
            name: 'rankPast3',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 1007238819144386474),
            name: 'birthplace',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 4339754572732378508),
            name: 'photo',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) {
  return obx.Store(getObjectBoxModel(),
      directory: directory,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 658255296345367868),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Member: obx_int.EntityDefinition<Member>(
        model: _entities[0],
        toOneRelations: (Member object) => [],
        toManyRelations: (Member object) => {},
        getId: (Member object) => object.id,
        setId: (Member object, int id) {
          object.id = id;
        },
        objectToFB: (Member object, fb.Builder fbb) {
          final dataTimeOffset = fbb.writeString(object.dataTime);
          final numberOffset = fbb.writeString(object.number);
          final nameOffset = fbb.writeString(object.name);
          final kana3Offset = fbb.writeString(object.kana3);
          final blanchOffset = fbb.writeString(object.blanch);
          final rankOffset = fbb.writeString(object.rank);
          final sexOffset = fbb.writeString(object.sex);
          final ageOffset = fbb.writeString(object.age);
          final heightOffset = fbb.writeString(object.height);
          final weightOffset = fbb.writeString(object.weight);
          final bloodOffset = fbb.writeString(object.blood);
          final winPointRateOffset = fbb.writeString(object.winPointRate);
          final winRate12Offset = fbb.writeString(object.winRate12);
          final rankPast1Offset = fbb.writeString(object.rankPast1);
          final rankPast2Offset = fbb.writeString(object.rankPast2);
          final rankPast3Offset = fbb.writeString(object.rankPast3);
          final birthplaceOffset = fbb.writeString(object.birthplace);
          final photoOffset = fbb.writeString(object.photo);
          fbb.startTable(20);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, dataTimeOffset);
          fbb.addOffset(2, numberOffset);
          fbb.addOffset(3, nameOffset);
          fbb.addOffset(4, kana3Offset);
          fbb.addOffset(5, blanchOffset);
          fbb.addOffset(6, rankOffset);
          fbb.addOffset(7, sexOffset);
          fbb.addOffset(8, ageOffset);
          fbb.addOffset(9, heightOffset);
          fbb.addOffset(10, weightOffset);
          fbb.addOffset(11, bloodOffset);
          fbb.addOffset(12, winPointRateOffset);
          fbb.addOffset(13, winRate12Offset);
          fbb.addOffset(14, rankPast1Offset);
          fbb.addOffset(15, rankPast2Offset);
          fbb.addOffset(16, rankPast3Offset);
          fbb.addOffset(17, birthplaceOffset);
          fbb.addOffset(18, photoOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final dataTimeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final numberParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final kana3Param = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final blanchParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final rankParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final sexParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final ageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 20, '');
          final heightParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 22, '');
          final weightParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 24, '');
          final bloodParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 26, '');
          final winPointRateParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 28, '');
          final winRate12Param = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 30, '');
          final rankPast1Param = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 32, '');
          final rankPast2Param = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 34, '');
          final rankPast3Param = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 36, '');
          final birthplaceParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 38, '');
          final photoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 40, '');
          final object = Member(
              id: idParam,
              dataTime: dataTimeParam,
              number: numberParam,
              name: nameParam,
              kana3: kana3Param,
              blanch: blanchParam,
              rank: rankParam,
              sex: sexParam,
              age: ageParam,
              height: heightParam,
              weight: weightParam,
              blood: bloodParam,
              winPointRate: winPointRateParam,
              winRate12: winRate12Param,
              rankPast1: rankPast1Param,
              rankPast2: rankPast2Param,
              rankPast3: rankPast3Param,
              birthplace: birthplaceParam,
              photo: photoParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Member] entity fields to define ObjectBox queries.
class Member_ {
  /// see [Member.id]
  static final id =
      obx.QueryIntegerProperty<Member>(_entities[0].properties[0]);

  /// see [Member.dataTime]
  static final dataTime =
      obx.QueryStringProperty<Member>(_entities[0].properties[1]);

  /// see [Member.number]
  static final number =
      obx.QueryStringProperty<Member>(_entities[0].properties[2]);

  /// see [Member.name]
  static final name =
      obx.QueryStringProperty<Member>(_entities[0].properties[3]);

  /// see [Member.kana3]
  static final kana3 =
      obx.QueryStringProperty<Member>(_entities[0].properties[4]);

  /// see [Member.blanch]
  static final blanch =
      obx.QueryStringProperty<Member>(_entities[0].properties[5]);

  /// see [Member.rank]
  static final rank =
      obx.QueryStringProperty<Member>(_entities[0].properties[6]);

  /// see [Member.sex]
  static final sex =
      obx.QueryStringProperty<Member>(_entities[0].properties[7]);

  /// see [Member.age]
  static final age =
      obx.QueryStringProperty<Member>(_entities[0].properties[8]);

  /// see [Member.height]
  static final height =
      obx.QueryStringProperty<Member>(_entities[0].properties[9]);

  /// see [Member.weight]
  static final weight =
      obx.QueryStringProperty<Member>(_entities[0].properties[10]);

  /// see [Member.blood]
  static final blood =
      obx.QueryStringProperty<Member>(_entities[0].properties[11]);

  /// see [Member.winPointRate]
  static final winPointRate =
      obx.QueryStringProperty<Member>(_entities[0].properties[12]);

  /// see [Member.winRate12]
  static final winRate12 =
      obx.QueryStringProperty<Member>(_entities[0].properties[13]);

  /// see [Member.rankPast1]
  static final rankPast1 =
      obx.QueryStringProperty<Member>(_entities[0].properties[14]);

  /// see [Member.rankPast2]
  static final rankPast2 =
      obx.QueryStringProperty<Member>(_entities[0].properties[15]);

  /// see [Member.rankPast3]
  static final rankPast3 =
      obx.QueryStringProperty<Member>(_entities[0].properties[16]);

  /// see [Member.birthplace]
  static final birthplace =
      obx.QueryStringProperty<Member>(_entities[0].properties[17]);

  /// see [Member.photo]
  static final photo =
      obx.QueryStringProperty<Member>(_entities[0].properties[18]);
}
