// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/member.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 658255296345367868),
    name: 'Member',
    lastPropertyId: const obx_int.IdUid(291, 8671285849071636797),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5659995356892222369),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(149, 2149005180014087940),
        name: 'vdt',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(23, 5270008024834213579),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(150, 7542185254415460648),
        name: 'vno',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(24, 4768864655550031859),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(151, 7513923259387751875),
        name: 'vname',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(25, 4016942519284639710),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(152, 2859276010643206905),
        name: 'vkana',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(26, 2597159100232749744),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(153, 7666221756698191831),
        name: 'vkana2',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(27, 8126710908781279921),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(154, 3445865969288230801),
        name: 'vkana3',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(28, 5774833790984272604),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(155, 9175742526398261282),
        name: 'vbr',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(29, 5484948310464662513),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(156, 5533070275765528893),
        name: 'vrank',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(30, 3084679671598664505),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(157, 3262154389697646459),
        name: 'vsex',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(31, 6631673757796725062),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(158, 260664652919978213),
        name: 'vGene',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(32, 4680881301180285878),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(159, 6834514648274674635),
        name: 'vwbday',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(160, 1608549671458558544),
        name: 'vgbday',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(161, 8088774588784053512),
        name: 'vage',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(162, 2433647275306597306),
        name: 'vht',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(163, 5488819523372675640),
        name: 'vwt',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(164, 8485970656401328992),
        name: 'vblood',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(165, 3376992462435809455),
        name: 'vbirth',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(166, 3234109585567402355),
        name: 'vphurl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(167, 2676960400196823055),
        name: 'vwinPt',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(168, 1759466354616673493),
        name: 'vwr12',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(169, 5148330058013278489),
        name: 'vp1Cnt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(170, 5391517270775441266),
        name: 'vp2Cnt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(171, 422910281880917668),
        name: 'vraceN',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(172, 7264230098389212408),
        name: 'vfinalN',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(173, 7553891637841561989),
        name: 'vwinN',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(174, 709023449823454838),
        name: 'vstAvg',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(175, 4347127579720915123),
        name: 'vrkP1',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(176, 437839060526303121),
        name: 'vrkP2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(177, 6140734219499307967),
        name: 'vrkP3',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(178, 2300125442412826128),
        name: 'vabPast',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(179, 4239448128112911977),
        name: 'vabLast',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(180, 6914137221386286483),
        name: 'vyear',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(181, 7571021555163636947),
        name: 'vseason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(182, 5148836316073417706),
        name: 'vsDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(183, 1434326772913598568),
        name: 'veDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(184, 133378393568409268),
        name: 'vc1Ent',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(185, 172213512120661900),
        name: 'vc2Ent',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(186, 8315915384618749003),
        name: 'vc3Ent',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(187, 3138421053076524338),
        name: 'vc4Ent',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(188, 5650551423545231924),
        name: 'vc5Ent',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(189, 8443146515625807223),
        name: 'vc6Ent',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(190, 7788501615233571454),
        name: 'vc1Wr',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(191, 5403210561006419258),
        name: 'vc2Wr',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(192, 6087058990956588778),
        name: 'vc3Wr',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(193, 5148357346016584751),
        name: 'vc4Wr',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(194, 2529234484427564442),
        name: 'vc5Wr',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(195, 8475912094762143265),
        name: 'vc6Wr',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(196, 9083294204728474115),
        name: 'vc1St',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(197, 6302177174043936332),
        name: 'vc2St',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(198, 350454069631830412),
        name: 'vc3St',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(199, 1637964227977313486),
        name: 'vc4St',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(200, 7062912059683549209),
        name: 'vc5St',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(201, 6330553543998162956),
        name: 'vc6St',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(202, 4382519430648620056),
        name: 'vc1So',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(203, 2797816500413202176),
        name: 'vc2So',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(204, 3510473542265211830),
        name: 'vc3So',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(205, 3637381011542653300),
        name: 'vc4So',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(206, 6451690634429064736),
        name: 'vc5So',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(207, 4103668417552334685),
        name: 'vc6So',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(208, 6949301413368799492),
        name: 'vc1P1',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(209, 4958417386904994977),
        name: 'vc2P1',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(210, 8428165636833987775),
        name: 'vc3P1',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(211, 2001504479936099433),
        name: 'vc4P1',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(212, 4739023337509489398),
        name: 'vc5P1',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(213, 8260544061275205433),
        name: 'vc6P1',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(214, 8995536405933708732),
        name: 'vc1P2',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(215, 2809839609543072060),
        name: 'vc2P2',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(216, 6322092398950192351),
        name: 'vc3P2',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(217, 7159304175513459129),
        name: 'vc4P2',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(218, 517748865554617914),
        name: 'vc5P2',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(219, 6498114465123576644),
        name: 'vc6P2',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(220, 2552201112337567232),
        name: 'vc1P3',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(221, 3181498623149743995),
        name: 'vc2P3',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(222, 3441753308456712176),
        name: 'vc3P3',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(223, 1070584512650973998),
        name: 'vc4P3',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(224, 7508543450494163639),
        name: 'vc5P3',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(225, 8860011207351254031),
        name: 'vc6P3',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(226, 4326347127487853228),
        name: 'vc1P4',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(227, 7808726889244709533),
        name: 'vc2P4',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(228, 62731403928922540),
        name: 'vc3P4',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(229, 1383197169982578792),
        name: 'vc4P4',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(230, 3648682980522162256),
        name: 'vc5P4',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(231, 502542579282368763),
        name: 'vc6P4',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(232, 5630339270417135171),
        name: 'vc1P5',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(233, 851771520131992892),
        name: 'vc2P5',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(234, 3393041119830193818),
        name: 'vc3P5',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(235, 2082595244392653490),
        name: 'vc4P5',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(236, 279112995131232201),
        name: 'vc5P5',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(237, 7004328840208108703),
        name: 'vc6P5',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(238, 6629517746262595683),
        name: 'vc1P6',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(239, 1688672801493998456),
        name: 'vc2P6',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(240, 4037715984974354193),
        name: 'vc3P6',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(241, 7785705176851067756),
        name: 'vc4P6',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(242, 2528135090355093445),
        name: 'vc5P6',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(243, 3863888221007896624),
        name: 'vc6P6',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(244, 5720471930388748520),
        name: 'vc1Fs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(245, 3542553604367581617),
        name: 'vc2Fs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(246, 4643364710181503113),
        name: 'vc3Fs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(247, 9103674853596048015),
        name: 'vc4Fs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(248, 7413804012267423009),
        name: 'vc5Fs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(249, 6856017246358184984),
        name: 'vc6Fs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(250, 6114142324723766322),
        name: 'vc1LsNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(251, 5041574753684855180),
        name: 'vc2LsNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(252, 5446579681205232588),
        name: 'vc3LsNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(253, 313623633471712043),
        name: 'vc4LsNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(254, 4710906763386951667),
        name: 'vc5LsNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(255, 5526898160018712680),
        name: 'vc6LsNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(256, 5186431701623888126),
        name: 'vc1LsR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(257, 4437101625780948377),
        name: 'vc2LsR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(258, 1407542808841447052),
        name: 'vc3LsR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(259, 6908802181210077812),
        name: 'vc4LsR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(260, 6391818669324524341),
        name: 'vc5LsR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(261, 4337371696176166400),
        name: 'vc6LsR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(262, 2327894330347942875),
        name: 'vc1WdNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(263, 5963219655264814023),
        name: 'vc2WdNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(264, 6056160105284556886),
        name: 'vc3WdNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(265, 2484749570266900847),
        name: 'vc4WdNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(266, 1182468618346683120),
        name: 'vc5WdNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(267, 2452045912145138350),
        name: 'vc6WdNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(268, 4354496918619976747),
        name: 'vc1WdR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(269, 5564117558022568212),
        name: 'vc2WdR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(270, 6528200916698157596),
        name: 'vc3WdR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(271, 221415435513524774),
        name: 'vc4WdR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(272, 474242092531643923),
        name: 'vc5WdR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(273, 2322980456583931644),
        name: 'vc6WdR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(274, 5484703588086880372),
        name: 'vc1InvNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(275, 3814458914264789700),
        name: 'vc2InvNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(276, 3624903125275254238),
        name: 'vc3InvNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(277, 1966239386144189600),
        name: 'vc4InvNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(278, 356045245755960755),
        name: 'vc5InvNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(279, 437439529246941916),
        name: 'vc6InvNr',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(280, 1773303665156241085),
        name: 'vc1InvR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(281, 4975573825168667220),
        name: 'vc2InvR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(282, 790160544982215158),
        name: 'vc3InvR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(283, 1618844576845530723),
        name: 'vc4InvR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(284, 3668412196748981327),
        name: 'vc5InvR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(285, 5577648292611165539),
        name: 'vc6InvR',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(286, 7345205951377780643),
        name: 'vc1InvOb',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(287, 3495365014944101067),
        name: 'vc2InvOb',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(288, 4018956825279982725),
        name: 'vc3InvOb',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(289, 8871778821303348182),
        name: 'vc4InvOb',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(290, 112965215249705293),
        name: 'vc5InvOb',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(291, 8671285849071636797),
        name: 'vc6InvOb',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 658255296345367868),
    lastIndexId: const obx_int.IdUid(32, 4680881301180285878),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [
      7669359111447592770,
      1657622077585215172,
      3562974060839934672,
      3169261751256621919,
      2397412152181717088,
      5340634122014368248,
      1979493720010181527,
      7867345923440885877,
      7531269257472910981,
      22821292483808053,
      4633875178206044215,
      5995365722047430684,
      6804525091863028340,
      486587669843704258,
      5656166229163549358,
      7750600661158324588,
      5782504250732298939,
      3127560166159612251,
      5476088881836951235,
      7608077555231110471,
      280384763984007213,
      5904872950383037033,
    ],
    retiredPropertyUids: const [
      5311703694034200539,
      5943826483361680632,
      6308664108243583555,
      8846676537573119614,
      5175693972718858319,
      6964318077685775740,
      4589279197445247119,
      2356490733601697843,
      919148478547667034,
      728448588195070265,
      4629124996623523366,
      7616541928478159120,
      4842146869039647723,
      5563685019089933465,
      7386000984543084385,
      3206822075286530144,
      6502025565454242714,
      1007238819144386474,
      4339754572732378508,
      2990073746427575158,
      7416923834742774636,
      7523426013340749203,
      4680132511344749913,
      6256213729802997996,
      8410614239284623814,
      4283913435647663899,
      74188166824651822,
      6922586012684142459,
      4987575879291559776,
      2651612065980842304,
      8420951689126147285,
      2798287411165930578,
      4283040212613205218,
      7065929595543637105,
      8356694847231549499,
      4307778047163282611,
      492538227565874537,
      3979181640722378541,
      5966712961733619181,
      7272732033736783100,
      2730201868099992915,
      2017482494582044620,
      8716060082646541934,
      6382160429419102654,
      1223201796261136228,
      2851744903952615279,
      7922308525436750562,
      1303214568481979397,
      7772243949855843816,
      2279802080753274566,
      1831683497203200924,
      1179079118307699268,
      1084632100062748686,
      986312834272600920,
      5511977770703529733,
      1992376159236877062,
      5625168110149993217,
      3501619423687194436,
      9101012003075018622,
      186986859415417884,
      140611906653012731,
      5451532050764726811,
      160162591682594195,
      2085641624420259172,
      4835017876073647929,
      8808233909118200040,
      3096648577534871017,
      7148786480683683442,
      4328845138461386045,
      355604752468557213,
      1511689575722365925,
      8679674068635237079,
      3679817684675493004,
      4434854291132245090,
      1568219891859641624,
      7627158537839059773,
      4207641373928739175,
      1297290283873219223,
      1119918827638020856,
      518218521810983410,
      4559121263247802264,
      1167824539002906696,
      90383418783874825,
      6076467256813808481,
      845589952658832770,
      3710935192949033661,
      5377376467458640825,
      8253065495475114227,
      3785725416722233727,
      7520713317887825691,
      4513865441997794364,
      5839185124073202352,
      6544559346694866763,
      8778283679022670395,
      5493946721761732596,
      1224172467118361976,
      7767271072541307920,
      2251982179487880634,
      2020582943726298257,
      1987727417436928516,
      3369309099468077662,
      8363118466870779633,
      814682780465991101,
      3538535996957722723,
      7923305736193913347,
      5136852803556826849,
      2487726705180941483,
      5631330239529681656,
      6453945100150393102,
      4621315808626266215,
      6165379246188435110,
      3545022502038978534,
      3585406490284940123,
      4315952601416181834,
      6399679229125714303,
      8738803172576163942,
      4507651018778754065,
      7955194855331937439,
      674042785608469397,
      1334749725829137670,
      5976316611230233149,
      3950109959485156018,
      9002703118198294633,
      7088104234334458293,
      7871917534078716626,
      5026569817708654584,
      7993340986626817414,
      6096046824973693344,
      404342849135427614,
      4808276500341318798,
      7648533001698223086,
      2001131029758196945,
      8368244538265167442,
      7223082873344225697,
      7684779523437102140,
      1851865979569479689,
      598228446332016309,
      6022412676403594674,
      8525397372338349291,
      7095600589025051740,
      3084436651674305025,
      5208394959554108125,
      5206377896499760499,
      4894004812393976172,
      1723879679029052258,
      4346842004957210948,
      9039883370374686682,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Member: obx_int.EntityDefinition<Member>(
      model: _entities[0],
      toOneRelations: (Member object) => [],
      toManyRelations: (Member object) => {},
      getId: (Member object) => object.id,
      setId: (Member object, int id) {
        object.id = id;
      },
      objectToFB: (Member object, fb.Builder fbb) {
        final vdtOffset = object.vdt == null
            ? null
            : fbb.writeString(object.vdt!);
        final vnoOffset = object.vno == null
            ? null
            : fbb.writeString(object.vno!);
        final vnameOffset = object.vname == null
            ? null
            : fbb.writeString(object.vname!);
        final vkanaOffset = object.vkana == null
            ? null
            : fbb.writeString(object.vkana!);
        final vkana2Offset = object.vkana2 == null
            ? null
            : fbb.writeString(object.vkana2!);
        final vkana3Offset = object.vkana3 == null
            ? null
            : fbb.writeString(object.vkana3!);
        final vbrOffset = object.vbr == null
            ? null
            : fbb.writeString(object.vbr!);
        final vrankOffset = object.vrank == null
            ? null
            : fbb.writeString(object.vrank!);
        final vwbdayOffset = object.vwbday == null
            ? null
            : fbb.writeString(object.vwbday!);
        final vgbdayOffset = object.vgbday == null
            ? null
            : fbb.writeString(object.vgbday!);
        final vbloodOffset = object.vblood == null
            ? null
            : fbb.writeString(object.vblood!);
        final vbirthOffset = object.vbirth == null
            ? null
            : fbb.writeString(object.vbirth!);
        final vphurlOffset = object.vphurl == null
            ? null
            : fbb.writeString(object.vphurl!);
        final vrkP1Offset = object.vrkP1 == null
            ? null
            : fbb.writeString(object.vrkP1!);
        final vrkP2Offset = object.vrkP2 == null
            ? null
            : fbb.writeString(object.vrkP2!);
        final vrkP3Offset = object.vrkP3 == null
            ? null
            : fbb.writeString(object.vrkP3!);
        final vseasonOffset = object.vseason == null
            ? null
            : fbb.writeString(object.vseason!);
        final vsDateOffset = object.vsDate == null
            ? null
            : fbb.writeString(object.vsDate!);
        final veDateOffset = object.veDate == null
            ? null
            : fbb.writeString(object.veDate!);
        fbb.startTable(292);
        fbb.addInt64(0, object.id);
        fbb.addOffset(148, vdtOffset);
        fbb.addOffset(149, vnoOffset);
        fbb.addOffset(150, vnameOffset);
        fbb.addOffset(151, vkanaOffset);
        fbb.addOffset(152, vkana2Offset);
        fbb.addOffset(153, vkana3Offset);
        fbb.addOffset(154, vbrOffset);
        fbb.addOffset(155, vrankOffset);
        fbb.addInt64(156, object.vsex);
        fbb.addInt64(157, object.vGene);
        fbb.addOffset(158, vwbdayOffset);
        fbb.addOffset(159, vgbdayOffset);
        fbb.addInt64(160, object.vage);
        fbb.addFloat64(161, object.vht);
        fbb.addFloat64(162, object.vwt);
        fbb.addOffset(163, vbloodOffset);
        fbb.addOffset(164, vbirthOffset);
        fbb.addOffset(165, vphurlOffset);
        fbb.addFloat64(166, object.vwinPt);
        fbb.addFloat64(167, object.vwr12);
        fbb.addInt64(168, object.vp1Cnt);
        fbb.addInt64(169, object.vp2Cnt);
        fbb.addInt64(170, object.vraceN);
        fbb.addInt64(171, object.vfinalN);
        fbb.addInt64(172, object.vwinN);
        fbb.addFloat64(173, object.vstAvg);
        fbb.addOffset(174, vrkP1Offset);
        fbb.addOffset(175, vrkP2Offset);
        fbb.addOffset(176, vrkP3Offset);
        fbb.addInt64(177, object.vabPast);
        fbb.addInt64(178, object.vabLast);
        fbb.addInt64(179, object.vyear);
        fbb.addOffset(180, vseasonOffset);
        fbb.addOffset(181, vsDateOffset);
        fbb.addOffset(182, veDateOffset);
        fbb.addInt64(183, object.vc1Ent);
        fbb.addInt64(184, object.vc2Ent);
        fbb.addInt64(185, object.vc3Ent);
        fbb.addInt64(186, object.vc4Ent);
        fbb.addInt64(187, object.vc5Ent);
        fbb.addInt64(188, object.vc6Ent);
        fbb.addFloat64(189, object.vc1Wr);
        fbb.addFloat64(190, object.vc2Wr);
        fbb.addFloat64(191, object.vc3Wr);
        fbb.addFloat64(192, object.vc4Wr);
        fbb.addFloat64(193, object.vc5Wr);
        fbb.addFloat64(194, object.vc6Wr);
        fbb.addFloat64(195, object.vc1St);
        fbb.addFloat64(196, object.vc2St);
        fbb.addFloat64(197, object.vc3St);
        fbb.addFloat64(198, object.vc4St);
        fbb.addFloat64(199, object.vc5St);
        fbb.addFloat64(200, object.vc6St);
        fbb.addFloat64(201, object.vc1So);
        fbb.addFloat64(202, object.vc2So);
        fbb.addFloat64(203, object.vc3So);
        fbb.addFloat64(204, object.vc4So);
        fbb.addFloat64(205, object.vc5So);
        fbb.addFloat64(206, object.vc6So);
        fbb.addInt64(207, object.vc1P1);
        fbb.addInt64(208, object.vc2P1);
        fbb.addInt64(209, object.vc3P1);
        fbb.addInt64(210, object.vc4P1);
        fbb.addInt64(211, object.vc5P1);
        fbb.addInt64(212, object.vc6P1);
        fbb.addInt64(213, object.vc1P2);
        fbb.addInt64(214, object.vc2P2);
        fbb.addInt64(215, object.vc3P2);
        fbb.addInt64(216, object.vc4P2);
        fbb.addInt64(217, object.vc5P2);
        fbb.addInt64(218, object.vc6P2);
        fbb.addInt64(219, object.vc1P3);
        fbb.addInt64(220, object.vc2P3);
        fbb.addInt64(221, object.vc3P3);
        fbb.addInt64(222, object.vc4P3);
        fbb.addInt64(223, object.vc5P3);
        fbb.addInt64(224, object.vc6P3);
        fbb.addInt64(225, object.vc1P4);
        fbb.addInt64(226, object.vc2P4);
        fbb.addInt64(227, object.vc3P4);
        fbb.addInt64(228, object.vc4P4);
        fbb.addInt64(229, object.vc5P4);
        fbb.addInt64(230, object.vc6P4);
        fbb.addInt64(231, object.vc1P5);
        fbb.addInt64(232, object.vc2P5);
        fbb.addInt64(233, object.vc3P5);
        fbb.addInt64(234, object.vc4P5);
        fbb.addInt64(235, object.vc5P5);
        fbb.addInt64(236, object.vc6P5);
        fbb.addInt64(237, object.vc1P6);
        fbb.addInt64(238, object.vc2P6);
        fbb.addInt64(239, object.vc3P6);
        fbb.addInt64(240, object.vc4P6);
        fbb.addInt64(241, object.vc5P6);
        fbb.addInt64(242, object.vc6P6);
        fbb.addInt64(243, object.vc1Fs);
        fbb.addInt64(244, object.vc2Fs);
        fbb.addInt64(245, object.vc3Fs);
        fbb.addInt64(246, object.vc4Fs);
        fbb.addInt64(247, object.vc5Fs);
        fbb.addInt64(248, object.vc6Fs);
        fbb.addInt64(249, object.vc1LsNr);
        fbb.addInt64(250, object.vc2LsNr);
        fbb.addInt64(251, object.vc3LsNr);
        fbb.addInt64(252, object.vc4LsNr);
        fbb.addInt64(253, object.vc5LsNr);
        fbb.addInt64(254, object.vc6LsNr);
        fbb.addInt64(255, object.vc1LsR);
        fbb.addInt64(256, object.vc2LsR);
        fbb.addInt64(257, object.vc3LsR);
        fbb.addInt64(258, object.vc4LsR);
        fbb.addInt64(259, object.vc5LsR);
        fbb.addInt64(260, object.vc6LsR);
        fbb.addInt64(261, object.vc1WdNr);
        fbb.addInt64(262, object.vc2WdNr);
        fbb.addInt64(263, object.vc3WdNr);
        fbb.addInt64(264, object.vc4WdNr);
        fbb.addInt64(265, object.vc5WdNr);
        fbb.addInt64(266, object.vc6WdNr);
        fbb.addInt64(267, object.vc1WdR);
        fbb.addInt64(268, object.vc2WdR);
        fbb.addInt64(269, object.vc3WdR);
        fbb.addInt64(270, object.vc4WdR);
        fbb.addInt64(271, object.vc5WdR);
        fbb.addInt64(272, object.vc6WdR);
        fbb.addInt64(273, object.vc1InvNr);
        fbb.addInt64(274, object.vc2InvNr);
        fbb.addInt64(275, object.vc3InvNr);
        fbb.addInt64(276, object.vc4InvNr);
        fbb.addInt64(277, object.vc5InvNr);
        fbb.addInt64(278, object.vc6InvNr);
        fbb.addInt64(279, object.vc1InvR);
        fbb.addInt64(280, object.vc2InvR);
        fbb.addInt64(281, object.vc3InvR);
        fbb.addInt64(282, object.vc4InvR);
        fbb.addInt64(283, object.vc5InvR);
        fbb.addInt64(284, object.vc6InvR);
        fbb.addInt64(285, object.vc1InvOb);
        fbb.addInt64(286, object.vc2InvOb);
        fbb.addInt64(287, object.vc3InvOb);
        fbb.addInt64(288, object.vc4InvOb);
        fbb.addInt64(289, object.vc5InvOb);
        fbb.addInt64(290, object.vc6InvOb);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final vdtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 300);
        final vnoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 302);
        final vnameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 304);
        final vkanaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 306);
        final vkana2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 308);
        final vkana3Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 310);
        final vbrParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 312);
        final vrankParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 314);
        final vsexParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          316,
        );
        final vGeneParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          318,
        );
        final vwbdayParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 320);
        final vgbdayParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 322);
        final vageParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          324,
        );
        final vhtParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          326,
        );
        final vwtParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          328,
        );
        final vbloodParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 330);
        final vbirthParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 332);
        final vphurlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 334);
        final vwinPtParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          336,
        );
        final vwr12Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          338,
        );
        final vp1CntParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          340,
        );
        final vp2CntParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          342,
        );
        final vraceNParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          344,
        );
        final vfinalNParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          346,
        );
        final vwinNParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          348,
        );
        final vstAvgParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          350,
        );
        final vrkP1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 352);
        final vrkP2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 354);
        final vrkP3Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 356);
        final vabPastParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          358,
        );
        final vabLastParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          360,
        );
        final vyearParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          362,
        );
        final vseasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 364);
        final vsDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 366);
        final veDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 368);
        final vc1EntParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          370,
        );
        final vc2EntParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          372,
        );
        final vc3EntParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          374,
        );
        final vc4EntParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          376,
        );
        final vc5EntParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          378,
        );
        final vc6EntParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          380,
        );
        final vc1WrParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          382,
        );
        final vc2WrParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          384,
        );
        final vc3WrParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          386,
        );
        final vc4WrParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          388,
        );
        final vc5WrParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          390,
        );
        final vc6WrParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          392,
        );
        final vc1StParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          394,
        );
        final vc2StParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          396,
        );
        final vc3StParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          398,
        );
        final vc4StParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          400,
        );
        final vc5StParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          402,
        );
        final vc6StParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          404,
        );
        final vc1SoParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          406,
        );
        final vc2SoParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          408,
        );
        final vc3SoParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          410,
        );
        final vc4SoParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          412,
        );
        final vc5SoParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          414,
        );
        final vc6SoParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          416,
        );
        final vc1P1Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          418,
        );
        final vc2P1Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          420,
        );
        final vc3P1Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          422,
        );
        final vc4P1Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          424,
        );
        final vc5P1Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          426,
        );
        final vc6P1Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          428,
        );
        final vc1P2Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          430,
        );
        final vc2P2Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          432,
        );
        final vc3P2Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          434,
        );
        final vc4P2Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          436,
        );
        final vc5P2Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          438,
        );
        final vc6P2Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          440,
        );
        final vc1P3Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          442,
        );
        final vc2P3Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          444,
        );
        final vc3P3Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          446,
        );
        final vc4P3Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          448,
        );
        final vc5P3Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          450,
        );
        final vc6P3Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          452,
        );
        final vc1P4Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          454,
        );
        final vc2P4Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          456,
        );
        final vc3P4Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          458,
        );
        final vc4P4Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          460,
        );
        final vc5P4Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          462,
        );
        final vc6P4Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          464,
        );
        final vc1P5Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          466,
        );
        final vc2P5Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          468,
        );
        final vc3P5Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          470,
        );
        final vc4P5Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          472,
        );
        final vc5P5Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          474,
        );
        final vc6P5Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          476,
        );
        final vc1P6Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          478,
        );
        final vc2P6Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          480,
        );
        final vc3P6Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          482,
        );
        final vc4P6Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          484,
        );
        final vc5P6Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          486,
        );
        final vc6P6Param = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          488,
        );
        final vc1FsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          490,
        );
        final vc2FsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          492,
        );
        final vc3FsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          494,
        );
        final vc4FsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          496,
        );
        final vc5FsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          498,
        );
        final vc6FsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          500,
        );
        final vc1LsNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          502,
        );
        final vc2LsNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          504,
        );
        final vc3LsNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          506,
        );
        final vc4LsNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          508,
        );
        final vc5LsNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          510,
        );
        final vc6LsNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          512,
        );
        final vc1LsRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          514,
        );
        final vc2LsRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          516,
        );
        final vc3LsRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          518,
        );
        final vc4LsRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          520,
        );
        final vc5LsRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          522,
        );
        final vc6LsRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          524,
        );
        final vc1WdNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          526,
        );
        final vc2WdNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          528,
        );
        final vc3WdNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          530,
        );
        final vc4WdNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          532,
        );
        final vc5WdNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          534,
        );
        final vc6WdNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          536,
        );
        final vc1WdRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          538,
        );
        final vc2WdRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          540,
        );
        final vc3WdRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          542,
        );
        final vc4WdRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          544,
        );
        final vc5WdRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          546,
        );
        final vc6WdRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          548,
        );
        final vc1InvNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          550,
        );
        final vc2InvNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          552,
        );
        final vc3InvNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          554,
        );
        final vc4InvNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          556,
        );
        final vc5InvNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          558,
        );
        final vc6InvNrParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          560,
        );
        final vc1InvRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          562,
        );
        final vc2InvRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          564,
        );
        final vc3InvRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          566,
        );
        final vc4InvRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          568,
        );
        final vc5InvRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          570,
        );
        final vc6InvRParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          572,
        );
        final vc1InvObParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          574,
        );
        final vc2InvObParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          576,
        );
        final vc3InvObParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          578,
        );
        final vc4InvObParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          580,
        );
        final vc5InvObParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          582,
        );
        final vc6InvObParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          584,
        );
        final object = Member(
          id: idParam,
          vdt: vdtParam,
          vno: vnoParam,
          vname: vnameParam,
          vkana: vkanaParam,
          vkana2: vkana2Param,
          vkana3: vkana3Param,
          vbr: vbrParam,
          vrank: vrankParam,
          vsex: vsexParam,
          vGene: vGeneParam,
          vwbday: vwbdayParam,
          vgbday: vgbdayParam,
          vage: vageParam,
          vht: vhtParam,
          vwt: vwtParam,
          vblood: vbloodParam,
          vbirth: vbirthParam,
          vphurl: vphurlParam,
          vwinPt: vwinPtParam,
          vwr12: vwr12Param,
          vp1Cnt: vp1CntParam,
          vp2Cnt: vp2CntParam,
          vraceN: vraceNParam,
          vfinalN: vfinalNParam,
          vwinN: vwinNParam,
          vstAvg: vstAvgParam,
          vrkP1: vrkP1Param,
          vrkP2: vrkP2Param,
          vrkP3: vrkP3Param,
          vabPast: vabPastParam,
          vabLast: vabLastParam,
          vyear: vyearParam,
          vseason: vseasonParam,
          vsDate: vsDateParam,
          veDate: veDateParam,
          vc1Ent: vc1EntParam,
          vc2Ent: vc2EntParam,
          vc3Ent: vc3EntParam,
          vc4Ent: vc4EntParam,
          vc5Ent: vc5EntParam,
          vc6Ent: vc6EntParam,
          vc1Wr: vc1WrParam,
          vc2Wr: vc2WrParam,
          vc3Wr: vc3WrParam,
          vc4Wr: vc4WrParam,
          vc5Wr: vc5WrParam,
          vc6Wr: vc6WrParam,
          vc1St: vc1StParam,
          vc2St: vc2StParam,
          vc3St: vc3StParam,
          vc4St: vc4StParam,
          vc5St: vc5StParam,
          vc6St: vc6StParam,
          vc1So: vc1SoParam,
          vc2So: vc2SoParam,
          vc3So: vc3SoParam,
          vc4So: vc4SoParam,
          vc5So: vc5SoParam,
          vc6So: vc6SoParam,
          vc1P1: vc1P1Param,
          vc2P1: vc2P1Param,
          vc3P1: vc3P1Param,
          vc4P1: vc4P1Param,
          vc5P1: vc5P1Param,
          vc6P1: vc6P1Param,
          vc1P2: vc1P2Param,
          vc2P2: vc2P2Param,
          vc3P2: vc3P2Param,
          vc4P2: vc4P2Param,
          vc5P2: vc5P2Param,
          vc6P2: vc6P2Param,
          vc1P3: vc1P3Param,
          vc2P3: vc2P3Param,
          vc3P3: vc3P3Param,
          vc4P3: vc4P3Param,
          vc5P3: vc5P3Param,
          vc6P3: vc6P3Param,
          vc1P4: vc1P4Param,
          vc2P4: vc2P4Param,
          vc3P4: vc3P4Param,
          vc4P4: vc4P4Param,
          vc5P4: vc5P4Param,
          vc6P4: vc6P4Param,
          vc1P5: vc1P5Param,
          vc2P5: vc2P5Param,
          vc3P5: vc3P5Param,
          vc4P5: vc4P5Param,
          vc5P5: vc5P5Param,
          vc6P5: vc6P5Param,
          vc1P6: vc1P6Param,
          vc2P6: vc2P6Param,
          vc3P6: vc3P6Param,
          vc4P6: vc4P6Param,
          vc5P6: vc5P6Param,
          vc6P6: vc6P6Param,
          vc1Fs: vc1FsParam,
          vc2Fs: vc2FsParam,
          vc3Fs: vc3FsParam,
          vc4Fs: vc4FsParam,
          vc5Fs: vc5FsParam,
          vc6Fs: vc6FsParam,
          vc1LsNr: vc1LsNrParam,
          vc2LsNr: vc2LsNrParam,
          vc3LsNr: vc3LsNrParam,
          vc4LsNr: vc4LsNrParam,
          vc5LsNr: vc5LsNrParam,
          vc6LsNr: vc6LsNrParam,
          vc1LsR: vc1LsRParam,
          vc2LsR: vc2LsRParam,
          vc3LsR: vc3LsRParam,
          vc4LsR: vc4LsRParam,
          vc5LsR: vc5LsRParam,
          vc6LsR: vc6LsRParam,
          vc1WdNr: vc1WdNrParam,
          vc2WdNr: vc2WdNrParam,
          vc3WdNr: vc3WdNrParam,
          vc4WdNr: vc4WdNrParam,
          vc5WdNr: vc5WdNrParam,
          vc6WdNr: vc6WdNrParam,
          vc1WdR: vc1WdRParam,
          vc2WdR: vc2WdRParam,
          vc3WdR: vc3WdRParam,
          vc4WdR: vc4WdRParam,
          vc5WdR: vc5WdRParam,
          vc6WdR: vc6WdRParam,
          vc1InvNr: vc1InvNrParam,
          vc2InvNr: vc2InvNrParam,
          vc3InvNr: vc3InvNrParam,
          vc4InvNr: vc4InvNrParam,
          vc5InvNr: vc5InvNrParam,
          vc6InvNr: vc6InvNrParam,
          vc1InvR: vc1InvRParam,
          vc2InvR: vc2InvRParam,
          vc3InvR: vc3InvRParam,
          vc4InvR: vc4InvRParam,
          vc5InvR: vc5InvRParam,
          vc6InvR: vc6InvRParam,
          vc1InvOb: vc1InvObParam,
          vc2InvOb: vc2InvObParam,
          vc3InvOb: vc3InvObParam,
          vc4InvOb: vc4InvObParam,
          vc5InvOb: vc5InvObParam,
          vc6InvOb: vc6InvObParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Member] entity fields to define ObjectBox queries.
class Member_ {
  /// See [Member.id].
  static final id = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[0],
  );

  /// See [Member.vdt].
  static final vdt = obx.QueryStringProperty<Member>(
    _entities[0].properties[1],
  );

  /// See [Member.vno].
  static final vno = obx.QueryStringProperty<Member>(
    _entities[0].properties[2],
  );

  /// See [Member.vname].
  static final vname = obx.QueryStringProperty<Member>(
    _entities[0].properties[3],
  );

  /// See [Member.vkana].
  static final vkana = obx.QueryStringProperty<Member>(
    _entities[0].properties[4],
  );

  /// See [Member.vkana2].
  static final vkana2 = obx.QueryStringProperty<Member>(
    _entities[0].properties[5],
  );

  /// See [Member.vkana3].
  static final vkana3 = obx.QueryStringProperty<Member>(
    _entities[0].properties[6],
  );

  /// See [Member.vbr].
  static final vbr = obx.QueryStringProperty<Member>(
    _entities[0].properties[7],
  );

  /// See [Member.vrank].
  static final vrank = obx.QueryStringProperty<Member>(
    _entities[0].properties[8],
  );

  /// See [Member.vsex].
  static final vsex = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[9],
  );

  /// See [Member.vGene].
  static final vGene = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[10],
  );

  /// See [Member.vwbday].
  static final vwbday = obx.QueryStringProperty<Member>(
    _entities[0].properties[11],
  );

  /// See [Member.vgbday].
  static final vgbday = obx.QueryStringProperty<Member>(
    _entities[0].properties[12],
  );

  /// See [Member.vage].
  static final vage = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[13],
  );

  /// See [Member.vht].
  static final vht = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[14],
  );

  /// See [Member.vwt].
  static final vwt = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[15],
  );

  /// See [Member.vblood].
  static final vblood = obx.QueryStringProperty<Member>(
    _entities[0].properties[16],
  );

  /// See [Member.vbirth].
  static final vbirth = obx.QueryStringProperty<Member>(
    _entities[0].properties[17],
  );

  /// See [Member.vphurl].
  static final vphurl = obx.QueryStringProperty<Member>(
    _entities[0].properties[18],
  );

  /// See [Member.vwinPt].
  static final vwinPt = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[19],
  );

  /// See [Member.vwr12].
  static final vwr12 = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[20],
  );

  /// See [Member.vp1Cnt].
  static final vp1Cnt = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[21],
  );

  /// See [Member.vp2Cnt].
  static final vp2Cnt = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[22],
  );

  /// See [Member.vraceN].
  static final vraceN = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[23],
  );

  /// See [Member.vfinalN].
  static final vfinalN = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[24],
  );

  /// See [Member.vwinN].
  static final vwinN = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[25],
  );

  /// See [Member.vstAvg].
  static final vstAvg = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[26],
  );

  /// See [Member.vrkP1].
  static final vrkP1 = obx.QueryStringProperty<Member>(
    _entities[0].properties[27],
  );

  /// See [Member.vrkP2].
  static final vrkP2 = obx.QueryStringProperty<Member>(
    _entities[0].properties[28],
  );

  /// See [Member.vrkP3].
  static final vrkP3 = obx.QueryStringProperty<Member>(
    _entities[0].properties[29],
  );

  /// See [Member.vabPast].
  static final vabPast = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[30],
  );

  /// See [Member.vabLast].
  static final vabLast = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[31],
  );

  /// See [Member.vyear].
  static final vyear = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[32],
  );

  /// See [Member.vseason].
  static final vseason = obx.QueryStringProperty<Member>(
    _entities[0].properties[33],
  );

  /// See [Member.vsDate].
  static final vsDate = obx.QueryStringProperty<Member>(
    _entities[0].properties[34],
  );

  /// See [Member.veDate].
  static final veDate = obx.QueryStringProperty<Member>(
    _entities[0].properties[35],
  );

  /// See [Member.vc1Ent].
  static final vc1Ent = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[36],
  );

  /// See [Member.vc2Ent].
  static final vc2Ent = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[37],
  );

  /// See [Member.vc3Ent].
  static final vc3Ent = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[38],
  );

  /// See [Member.vc4Ent].
  static final vc4Ent = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[39],
  );

  /// See [Member.vc5Ent].
  static final vc5Ent = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[40],
  );

  /// See [Member.vc6Ent].
  static final vc6Ent = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[41],
  );

  /// See [Member.vc1Wr].
  static final vc1Wr = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[42],
  );

  /// See [Member.vc2Wr].
  static final vc2Wr = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[43],
  );

  /// See [Member.vc3Wr].
  static final vc3Wr = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[44],
  );

  /// See [Member.vc4Wr].
  static final vc4Wr = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[45],
  );

  /// See [Member.vc5Wr].
  static final vc5Wr = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[46],
  );

  /// See [Member.vc6Wr].
  static final vc6Wr = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[47],
  );

  /// See [Member.vc1St].
  static final vc1St = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[48],
  );

  /// See [Member.vc2St].
  static final vc2St = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[49],
  );

  /// See [Member.vc3St].
  static final vc3St = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[50],
  );

  /// See [Member.vc4St].
  static final vc4St = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[51],
  );

  /// See [Member.vc5St].
  static final vc5St = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[52],
  );

  /// See [Member.vc6St].
  static final vc6St = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[53],
  );

  /// See [Member.vc1So].
  static final vc1So = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[54],
  );

  /// See [Member.vc2So].
  static final vc2So = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[55],
  );

  /// See [Member.vc3So].
  static final vc3So = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[56],
  );

  /// See [Member.vc4So].
  static final vc4So = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[57],
  );

  /// See [Member.vc5So].
  static final vc5So = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[58],
  );

  /// See [Member.vc6So].
  static final vc6So = obx.QueryDoubleProperty<Member>(
    _entities[0].properties[59],
  );

  /// See [Member.vc1P1].
  static final vc1P1 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[60],
  );

  /// See [Member.vc2P1].
  static final vc2P1 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[61],
  );

  /// See [Member.vc3P1].
  static final vc3P1 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[62],
  );

  /// See [Member.vc4P1].
  static final vc4P1 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[63],
  );

  /// See [Member.vc5P1].
  static final vc5P1 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[64],
  );

  /// See [Member.vc6P1].
  static final vc6P1 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[65],
  );

  /// See [Member.vc1P2].
  static final vc1P2 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[66],
  );

  /// See [Member.vc2P2].
  static final vc2P2 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[67],
  );

  /// See [Member.vc3P2].
  static final vc3P2 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[68],
  );

  /// See [Member.vc4P2].
  static final vc4P2 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[69],
  );

  /// See [Member.vc5P2].
  static final vc5P2 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[70],
  );

  /// See [Member.vc6P2].
  static final vc6P2 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[71],
  );

  /// See [Member.vc1P3].
  static final vc1P3 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[72],
  );

  /// See [Member.vc2P3].
  static final vc2P3 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[73],
  );

  /// See [Member.vc3P3].
  static final vc3P3 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[74],
  );

  /// See [Member.vc4P3].
  static final vc4P3 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[75],
  );

  /// See [Member.vc5P3].
  static final vc5P3 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[76],
  );

  /// See [Member.vc6P3].
  static final vc6P3 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[77],
  );

  /// See [Member.vc1P4].
  static final vc1P4 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[78],
  );

  /// See [Member.vc2P4].
  static final vc2P4 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[79],
  );

  /// See [Member.vc3P4].
  static final vc3P4 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[80],
  );

  /// See [Member.vc4P4].
  static final vc4P4 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[81],
  );

  /// See [Member.vc5P4].
  static final vc5P4 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[82],
  );

  /// See [Member.vc6P4].
  static final vc6P4 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[83],
  );

  /// See [Member.vc1P5].
  static final vc1P5 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[84],
  );

  /// See [Member.vc2P5].
  static final vc2P5 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[85],
  );

  /// See [Member.vc3P5].
  static final vc3P5 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[86],
  );

  /// See [Member.vc4P5].
  static final vc4P5 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[87],
  );

  /// See [Member.vc5P5].
  static final vc5P5 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[88],
  );

  /// See [Member.vc6P5].
  static final vc6P5 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[89],
  );

  /// See [Member.vc1P6].
  static final vc1P6 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[90],
  );

  /// See [Member.vc2P6].
  static final vc2P6 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[91],
  );

  /// See [Member.vc3P6].
  static final vc3P6 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[92],
  );

  /// See [Member.vc4P6].
  static final vc4P6 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[93],
  );

  /// See [Member.vc5P6].
  static final vc5P6 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[94],
  );

  /// See [Member.vc6P6].
  static final vc6P6 = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[95],
  );

  /// See [Member.vc1Fs].
  static final vc1Fs = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[96],
  );

  /// See [Member.vc2Fs].
  static final vc2Fs = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[97],
  );

  /// See [Member.vc3Fs].
  static final vc3Fs = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[98],
  );

  /// See [Member.vc4Fs].
  static final vc4Fs = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[99],
  );

  /// See [Member.vc5Fs].
  static final vc5Fs = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[100],
  );

  /// See [Member.vc6Fs].
  static final vc6Fs = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[101],
  );

  /// See [Member.vc1LsNr].
  static final vc1LsNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[102],
  );

  /// See [Member.vc2LsNr].
  static final vc2LsNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[103],
  );

  /// See [Member.vc3LsNr].
  static final vc3LsNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[104],
  );

  /// See [Member.vc4LsNr].
  static final vc4LsNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[105],
  );

  /// See [Member.vc5LsNr].
  static final vc5LsNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[106],
  );

  /// See [Member.vc6LsNr].
  static final vc6LsNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[107],
  );

  /// See [Member.vc1LsR].
  static final vc1LsR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[108],
  );

  /// See [Member.vc2LsR].
  static final vc2LsR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[109],
  );

  /// See [Member.vc3LsR].
  static final vc3LsR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[110],
  );

  /// See [Member.vc4LsR].
  static final vc4LsR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[111],
  );

  /// See [Member.vc5LsR].
  static final vc5LsR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[112],
  );

  /// See [Member.vc6LsR].
  static final vc6LsR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[113],
  );

  /// See [Member.vc1WdNr].
  static final vc1WdNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[114],
  );

  /// See [Member.vc2WdNr].
  static final vc2WdNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[115],
  );

  /// See [Member.vc3WdNr].
  static final vc3WdNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[116],
  );

  /// See [Member.vc4WdNr].
  static final vc4WdNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[117],
  );

  /// See [Member.vc5WdNr].
  static final vc5WdNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[118],
  );

  /// See [Member.vc6WdNr].
  static final vc6WdNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[119],
  );

  /// See [Member.vc1WdR].
  static final vc1WdR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[120],
  );

  /// See [Member.vc2WdR].
  static final vc2WdR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[121],
  );

  /// See [Member.vc3WdR].
  static final vc3WdR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[122],
  );

  /// See [Member.vc4WdR].
  static final vc4WdR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[123],
  );

  /// See [Member.vc5WdR].
  static final vc5WdR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[124],
  );

  /// See [Member.vc6WdR].
  static final vc6WdR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[125],
  );

  /// See [Member.vc1InvNr].
  static final vc1InvNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[126],
  );

  /// See [Member.vc2InvNr].
  static final vc2InvNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[127],
  );

  /// See [Member.vc3InvNr].
  static final vc3InvNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[128],
  );

  /// See [Member.vc4InvNr].
  static final vc4InvNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[129],
  );

  /// See [Member.vc5InvNr].
  static final vc5InvNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[130],
  );

  /// See [Member.vc6InvNr].
  static final vc6InvNr = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[131],
  );

  /// See [Member.vc1InvR].
  static final vc1InvR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[132],
  );

  /// See [Member.vc2InvR].
  static final vc2InvR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[133],
  );

  /// See [Member.vc3InvR].
  static final vc3InvR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[134],
  );

  /// See [Member.vc4InvR].
  static final vc4InvR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[135],
  );

  /// See [Member.vc5InvR].
  static final vc5InvR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[136],
  );

  /// See [Member.vc6InvR].
  static final vc6InvR = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[137],
  );

  /// See [Member.vc1InvOb].
  static final vc1InvOb = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[138],
  );

  /// See [Member.vc2InvOb].
  static final vc2InvOb = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[139],
  );

  /// See [Member.vc3InvOb].
  static final vc3InvOb = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[140],
  );

  /// See [Member.vc4InvOb].
  static final vc4InvOb = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[141],
  );

  /// See [Member.vc5InvOb].
  static final vc5InvOb = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[142],
  );

  /// See [Member.vc6InvOb].
  static final vc6InvOb = obx.QueryIntegerProperty<Member>(
    _entities[0].properties[143],
  );
}
