// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/member.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 658255296345367868),
      name: 'Member',
      lastPropertyId: const obx_int.IdUid(75, 4434854291132245090),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5659995356892222369),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8846676537573119614),
            name: 'dataTime',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5175693972718858319),
            name: 'number',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6964318077685775740),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4589279197445247119),
            name: 'kana3',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6308664108243583555),
            name: 'blanch',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2356490733601697843),
            name: 'rank',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 919148478547667034),
            name: 'sex',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 728448588195070265),
            name: 'age',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4629124996623523366),
            name: 'height',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 7616541928478159120),
            name: 'weight',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 4842146869039647723),
            name: 'blood',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 5563685019089933465),
            name: 'winRate12',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 7386000984543084385),
            name: 'rankPast1',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 3206822075286530144),
            name: 'rankPast2',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 6502025565454242714),
            name: 'rankPast3',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 1007238819144386474),
            name: 'birthplace',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 4339754572732378508),
            name: 'photo',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 2990073746427575158),
            name: 'kana',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(21, 7416923834742774636),
            name: 'kana2',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(22, 7523426013340749203),
            name: 'wBirthday',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(23, 4680132511344749913),
            name: 'gBirthday',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(24, 6256213729802997996),
            name: 'firstPlaceCount',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(25, 8410614239284623814),
            name: 'secondPlaceCount',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(26, 4283913435647663899),
            name: 'numberOfRace',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(27, 74188166824651822),
            name: 'numberOfFinals',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(28, 6922586012684142459),
            name: 'numberOfWins',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(29, 4987575879291559776),
            name: 'startTiming',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(30, 2651612065980842304),
            name: 'pastAbilityScore',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(31, 8420951689126147285),
            name: 'lastAbilityScore',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(32, 2798287411165930578),
            name: 'dataYear',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(33, 4283040212613205218),
            name: 'dataSeason',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(34, 7065929595543637105),
            name: 'startDate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(35, 8356694847231549499),
            name: 'endDate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(36, 4307778047163282611),
            name: 'generation',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(37, 492538227565874537),
            name: 'nameKana',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(39, 3979181640722378541),
            name: 'winPointRate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(40, 5966712961733619181),
            name: 'numberOfEntries1',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(41, 7272732033736783100),
            name: 'numberOfEntries2',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(42, 2730201868099992915),
            name: 'numberOfEntries3',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(43, 2017482494582044620),
            name: 'numberOfEntries4',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(44, 8716060082646541934),
            name: 'numberOfEntries5',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(45, 6382160429419102654),
            name: 'numberOfEntries6',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(46, 1223201796261136228),
            name: 'winRate121',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(47, 2851744903952615279),
            name: 'winRate122',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(48, 7922308525436750562),
            name: 'winRate123',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(49, 1303214568481979397),
            name: 'winRate124',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(50, 7772243949855843816),
            name: 'winRate125',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(51, 2279802080753274566),
            name: 'winRate126',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(52, 1831683497203200924),
            name: 'startTime1',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(53, 1179079118307699268),
            name: 'startTime2',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(54, 1084632100062748686),
            name: 'startTime3',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(55, 986312834272600920),
            name: 'startTime4',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(56, 5511977770703529733),
            name: 'startTime5',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(57, 1992376159236877062),
            name: 'startTime6',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(58, 5625168110149993217),
            name: 'firstPlace1',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(59, 3501619423687194436),
            name: 'firstPlace2',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(60, 9101012003075018622),
            name: 'firstPlace3',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(61, 186986859415417884),
            name: 'firstPlace4',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(62, 140611906653012731),
            name: 'firstPlace5',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(63, 5451532050764726811),
            name: 'firstPlace6',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(64, 160162591682594195),
            name: 'secondPlace1',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(65, 2085641624420259172),
            name: 'secondPlace2',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(66, 4835017876073647929),
            name: 'secondPlace3',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(67, 8808233909118200040),
            name: 'secondPlace4',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(68, 3096648577534871017),
            name: 'secondPlace5',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(69, 7148786480683683442),
            name: 'secondPlace6',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(70, 4328845138461386045),
            name: 'thirdPlace1',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(71, 355604752468557213),
            name: 'thirdPlace2',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(72, 1511689575722365925),
            name: 'thirdPlace3',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(73, 8679674068635237079),
            name: 'thirdPlace4',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(74, 3679817684675493004),
            name: 'thirdPlace5',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(75, 4434854291132245090),
            name: 'thirdPlace6',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 658255296345367868),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [5311703694034200539, 5943826483361680632],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Member: obx_int.EntityDefinition<Member>(
        model: _entities[0],
        toOneRelations: (Member object) => [],
        toManyRelations: (Member object) => {},
        getId: (Member object) => object.id,
        setId: (Member object, int id) {
          object.id = id;
        },
        objectToFB: (Member object, fb.Builder fbb) {
          final dataTimeOffset = object.dataTime == null
              ? null
              : fbb.writeString(object.dataTime!);
          final numberOffset =
              object.number == null ? null : fbb.writeString(object.number!);
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final kana3Offset =
              object.kana3 == null ? null : fbb.writeString(object.kana3!);
          final blanchOffset =
              object.blanch == null ? null : fbb.writeString(object.blanch!);
          final rankOffset =
              object.rank == null ? null : fbb.writeString(object.rank!);
          final sexOffset =
              object.sex == null ? null : fbb.writeString(object.sex!);
          final ageOffset =
              object.age == null ? null : fbb.writeString(object.age!);
          final heightOffset =
              object.height == null ? null : fbb.writeString(object.height!);
          final weightOffset =
              object.weight == null ? null : fbb.writeString(object.weight!);
          final bloodOffset =
              object.blood == null ? null : fbb.writeString(object.blood!);
          final winRate12Offset = object.winRate12 == null
              ? null
              : fbb.writeString(object.winRate12!);
          final rankPast1Offset = object.rankPast1 == null
              ? null
              : fbb.writeString(object.rankPast1!);
          final rankPast2Offset = object.rankPast2 == null
              ? null
              : fbb.writeString(object.rankPast2!);
          final rankPast3Offset = object.rankPast3 == null
              ? null
              : fbb.writeString(object.rankPast3!);
          final birthplaceOffset = object.birthplace == null
              ? null
              : fbb.writeString(object.birthplace!);
          final photoOffset =
              object.photo == null ? null : fbb.writeString(object.photo!);
          final kanaOffset =
              object.kana == null ? null : fbb.writeString(object.kana!);
          final kana2Offset =
              object.kana2 == null ? null : fbb.writeString(object.kana2!);
          final wBirthdayOffset = object.wBirthday == null
              ? null
              : fbb.writeString(object.wBirthday!);
          final gBirthdayOffset = object.gBirthday == null
              ? null
              : fbb.writeString(object.gBirthday!);
          final firstPlaceCountOffset = object.firstPlaceCount == null
              ? null
              : fbb.writeString(object.firstPlaceCount!);
          final secondPlaceCountOffset = object.secondPlaceCount == null
              ? null
              : fbb.writeString(object.secondPlaceCount!);
          final numberOfRaceOffset = object.numberOfRace == null
              ? null
              : fbb.writeString(object.numberOfRace!);
          final numberOfFinalsOffset = object.numberOfFinals == null
              ? null
              : fbb.writeString(object.numberOfFinals!);
          final numberOfWinsOffset = object.numberOfWins == null
              ? null
              : fbb.writeString(object.numberOfWins!);
          final startTimingOffset = object.startTiming == null
              ? null
              : fbb.writeString(object.startTiming!);
          final pastAbilityScoreOffset = object.pastAbilityScore == null
              ? null
              : fbb.writeString(object.pastAbilityScore!);
          final lastAbilityScoreOffset = object.lastAbilityScore == null
              ? null
              : fbb.writeString(object.lastAbilityScore!);
          final dataYearOffset = object.dataYear == null
              ? null
              : fbb.writeString(object.dataYear!);
          final dataSeasonOffset = object.dataSeason == null
              ? null
              : fbb.writeString(object.dataSeason!);
          final startDateOffset = object.startDate == null
              ? null
              : fbb.writeString(object.startDate!);
          final endDateOffset =
              object.endDate == null ? null : fbb.writeString(object.endDate!);
          final generationOffset = object.generation == null
              ? null
              : fbb.writeString(object.generation!);
          final nameKanaOffset = object.nameKana == null
              ? null
              : fbb.writeString(object.nameKana!);
          final winPointRateOffset = object.winPointRate == null
              ? null
              : fbb.writeString(object.winPointRate!);
          final numberOfEntries1Offset = object.numberOfEntries1 == null
              ? null
              : fbb.writeString(object.numberOfEntries1!);
          final numberOfEntries2Offset = object.numberOfEntries2 == null
              ? null
              : fbb.writeString(object.numberOfEntries2!);
          final numberOfEntries3Offset = object.numberOfEntries3 == null
              ? null
              : fbb.writeString(object.numberOfEntries3!);
          final numberOfEntries4Offset = object.numberOfEntries4 == null
              ? null
              : fbb.writeString(object.numberOfEntries4!);
          final numberOfEntries5Offset = object.numberOfEntries5 == null
              ? null
              : fbb.writeString(object.numberOfEntries5!);
          final numberOfEntries6Offset = object.numberOfEntries6 == null
              ? null
              : fbb.writeString(object.numberOfEntries6!);
          final winRate121Offset = object.winRate121 == null
              ? null
              : fbb.writeString(object.winRate121!);
          final winRate122Offset = object.winRate122 == null
              ? null
              : fbb.writeString(object.winRate122!);
          final winRate123Offset = object.winRate123 == null
              ? null
              : fbb.writeString(object.winRate123!);
          final winRate124Offset = object.winRate124 == null
              ? null
              : fbb.writeString(object.winRate124!);
          final winRate125Offset = object.winRate125 == null
              ? null
              : fbb.writeString(object.winRate125!);
          final winRate126Offset = object.winRate126 == null
              ? null
              : fbb.writeString(object.winRate126!);
          final startTime1Offset = object.startTime1 == null
              ? null
              : fbb.writeString(object.startTime1!);
          final startTime2Offset = object.startTime2 == null
              ? null
              : fbb.writeString(object.startTime2!);
          final startTime3Offset = object.startTime3 == null
              ? null
              : fbb.writeString(object.startTime3!);
          final startTime4Offset = object.startTime4 == null
              ? null
              : fbb.writeString(object.startTime4!);
          final startTime5Offset = object.startTime5 == null
              ? null
              : fbb.writeString(object.startTime5!);
          final startTime6Offset = object.startTime6 == null
              ? null
              : fbb.writeString(object.startTime6!);
          final firstPlace1Offset = object.firstPlace1 == null
              ? null
              : fbb.writeString(object.firstPlace1!);
          final firstPlace2Offset = object.firstPlace2 == null
              ? null
              : fbb.writeString(object.firstPlace2!);
          final firstPlace3Offset = object.firstPlace3 == null
              ? null
              : fbb.writeString(object.firstPlace3!);
          final firstPlace4Offset = object.firstPlace4 == null
              ? null
              : fbb.writeString(object.firstPlace4!);
          final firstPlace5Offset = object.firstPlace5 == null
              ? null
              : fbb.writeString(object.firstPlace5!);
          final firstPlace6Offset = object.firstPlace6 == null
              ? null
              : fbb.writeString(object.firstPlace6!);
          final secondPlace1Offset = object.secondPlace1 == null
              ? null
              : fbb.writeString(object.secondPlace1!);
          final secondPlace2Offset = object.secondPlace2 == null
              ? null
              : fbb.writeString(object.secondPlace2!);
          final secondPlace3Offset = object.secondPlace3 == null
              ? null
              : fbb.writeString(object.secondPlace3!);
          final secondPlace4Offset = object.secondPlace4 == null
              ? null
              : fbb.writeString(object.secondPlace4!);
          final secondPlace5Offset = object.secondPlace5 == null
              ? null
              : fbb.writeString(object.secondPlace5!);
          final secondPlace6Offset = object.secondPlace6 == null
              ? null
              : fbb.writeString(object.secondPlace6!);
          final thirdPlace1Offset = object.thirdPlace1 == null
              ? null
              : fbb.writeString(object.thirdPlace1!);
          final thirdPlace2Offset = object.thirdPlace2 == null
              ? null
              : fbb.writeString(object.thirdPlace2!);
          final thirdPlace3Offset = object.thirdPlace3 == null
              ? null
              : fbb.writeString(object.thirdPlace3!);
          final thirdPlace4Offset = object.thirdPlace4 == null
              ? null
              : fbb.writeString(object.thirdPlace4!);
          final thirdPlace5Offset = object.thirdPlace5 == null
              ? null
              : fbb.writeString(object.thirdPlace5!);
          final thirdPlace6Offset = object.thirdPlace6 == null
              ? null
              : fbb.writeString(object.thirdPlace6!);
          fbb.startTable(76);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, dataTimeOffset);
          fbb.addOffset(2, numberOffset);
          fbb.addOffset(3, nameOffset);
          fbb.addOffset(4, kana3Offset);
          fbb.addOffset(5, blanchOffset);
          fbb.addOffset(6, rankOffset);
          fbb.addOffset(7, sexOffset);
          fbb.addOffset(8, ageOffset);
          fbb.addOffset(9, heightOffset);
          fbb.addOffset(10, weightOffset);
          fbb.addOffset(11, bloodOffset);
          fbb.addOffset(13, winRate12Offset);
          fbb.addOffset(14, rankPast1Offset);
          fbb.addOffset(15, rankPast2Offset);
          fbb.addOffset(16, rankPast3Offset);
          fbb.addOffset(17, birthplaceOffset);
          fbb.addOffset(18, photoOffset);
          fbb.addOffset(19, kanaOffset);
          fbb.addOffset(20, kana2Offset);
          fbb.addOffset(21, wBirthdayOffset);
          fbb.addOffset(22, gBirthdayOffset);
          fbb.addOffset(23, firstPlaceCountOffset);
          fbb.addOffset(24, secondPlaceCountOffset);
          fbb.addOffset(25, numberOfRaceOffset);
          fbb.addOffset(26, numberOfFinalsOffset);
          fbb.addOffset(27, numberOfWinsOffset);
          fbb.addOffset(28, startTimingOffset);
          fbb.addOffset(29, pastAbilityScoreOffset);
          fbb.addOffset(30, lastAbilityScoreOffset);
          fbb.addOffset(31, dataYearOffset);
          fbb.addOffset(32, dataSeasonOffset);
          fbb.addOffset(33, startDateOffset);
          fbb.addOffset(34, endDateOffset);
          fbb.addOffset(35, generationOffset);
          fbb.addOffset(36, nameKanaOffset);
          fbb.addOffset(38, winPointRateOffset);
          fbb.addOffset(39, numberOfEntries1Offset);
          fbb.addOffset(40, numberOfEntries2Offset);
          fbb.addOffset(41, numberOfEntries3Offset);
          fbb.addOffset(42, numberOfEntries4Offset);
          fbb.addOffset(43, numberOfEntries5Offset);
          fbb.addOffset(44, numberOfEntries6Offset);
          fbb.addOffset(45, winRate121Offset);
          fbb.addOffset(46, winRate122Offset);
          fbb.addOffset(47, winRate123Offset);
          fbb.addOffset(48, winRate124Offset);
          fbb.addOffset(49, winRate125Offset);
          fbb.addOffset(50, winRate126Offset);
          fbb.addOffset(51, startTime1Offset);
          fbb.addOffset(52, startTime2Offset);
          fbb.addOffset(53, startTime3Offset);
          fbb.addOffset(54, startTime4Offset);
          fbb.addOffset(55, startTime5Offset);
          fbb.addOffset(56, startTime6Offset);
          fbb.addOffset(57, firstPlace1Offset);
          fbb.addOffset(58, firstPlace2Offset);
          fbb.addOffset(59, firstPlace3Offset);
          fbb.addOffset(60, firstPlace4Offset);
          fbb.addOffset(61, firstPlace5Offset);
          fbb.addOffset(62, firstPlace6Offset);
          fbb.addOffset(63, secondPlace1Offset);
          fbb.addOffset(64, secondPlace2Offset);
          fbb.addOffset(65, secondPlace3Offset);
          fbb.addOffset(66, secondPlace4Offset);
          fbb.addOffset(67, secondPlace5Offset);
          fbb.addOffset(68, secondPlace6Offset);
          fbb.addOffset(69, thirdPlace1Offset);
          fbb.addOffset(70, thirdPlace2Offset);
          fbb.addOffset(71, thirdPlace3Offset);
          fbb.addOffset(72, thirdPlace4Offset);
          fbb.addOffset(73, thirdPlace5Offset);
          fbb.addOffset(74, thirdPlace6Offset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final dataTimeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final numberParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final nameKanaParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 76);
          final kanaParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 42);
          final kana2Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 44);
          final kana3Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final blanchParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final rankParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final wBirthdayParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 46);
          final gBirthdayParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 48);
          final sexParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final ageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final heightParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 22);
          final weightParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 24);
          final bloodParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 26);
          final birthplaceParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 38);
          final photoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 40);
          final winPointRateParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 80);
          final winRate12Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 30);
          final firstPlaceCountParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 50);
          final secondPlaceCountParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 52);
          final numberOfRaceParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 54);
          final numberOfFinalsParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 56);
          final numberOfWinsParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 58);
          final startTimingParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 60);
          final rankPast1Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 32);
          final rankPast2Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 34);
          final rankPast3Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 36);
          final pastAbilityScoreParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 62);
          final lastAbilityScoreParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 64);
          final dataYearParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 66);
          final dataSeasonParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 68);
          final startDateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 70);
          final endDateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 72);
          final generationParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 74);
          final numberOfEntries1Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 82);
          final numberOfEntries2Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 84);
          final numberOfEntries3Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 86);
          final numberOfEntries4Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 88);
          final numberOfEntries5Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 90);
          final numberOfEntries6Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 92);
          final winRate121Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 94);
          final winRate122Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 96);
          final winRate123Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 98);
          final winRate124Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 100);
          final winRate125Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 102);
          final winRate126Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 104);
          final startTime1Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 106);
          final startTime2Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 108);
          final startTime3Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 110);
          final startTime4Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 112);
          final startTime5Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 114);
          final startTime6Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 116);
          final firstPlace1Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 118);
          final firstPlace2Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 120);
          final firstPlace3Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 122);
          final firstPlace4Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 124);
          final firstPlace5Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 126);
          final firstPlace6Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 128);
          final secondPlace1Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 130);
          final secondPlace2Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 132);
          final secondPlace3Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 134);
          final secondPlace4Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 136);
          final secondPlace5Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 138);
          final secondPlace6Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 140);
          final thirdPlace1Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 142);
          final thirdPlace2Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 144);
          final thirdPlace3Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 146);
          final thirdPlace4Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 148);
          final thirdPlace5Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 150);
          final thirdPlace6Param =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 152);
          final object = Member(
              id: idParam,
              dataTime: dataTimeParam,
              number: numberParam,
              name: nameParam,
              nameKana: nameKanaParam,
              kana: kanaParam,
              kana2: kana2Param,
              kana3: kana3Param,
              blanch: blanchParam,
              rank: rankParam,
              wBirthday: wBirthdayParam,
              gBirthday: gBirthdayParam,
              sex: sexParam,
              age: ageParam,
              height: heightParam,
              weight: weightParam,
              blood: bloodParam,
              birthplace: birthplaceParam,
              photo: photoParam,
              winPointRate: winPointRateParam,
              winRate12: winRate12Param,
              firstPlaceCount: firstPlaceCountParam,
              secondPlaceCount: secondPlaceCountParam,
              numberOfRace: numberOfRaceParam,
              numberOfFinals: numberOfFinalsParam,
              numberOfWins: numberOfWinsParam,
              startTiming: startTimingParam,
              rankPast1: rankPast1Param,
              rankPast2: rankPast2Param,
              rankPast3: rankPast3Param,
              pastAbilityScore: pastAbilityScoreParam,
              lastAbilityScore: lastAbilityScoreParam,
              dataYear: dataYearParam,
              dataSeason: dataSeasonParam,
              startDate: startDateParam,
              endDate: endDateParam,
              generation: generationParam,
              numberOfEntries1: numberOfEntries1Param,
              numberOfEntries2: numberOfEntries2Param,
              numberOfEntries3: numberOfEntries3Param,
              numberOfEntries4: numberOfEntries4Param,
              numberOfEntries5: numberOfEntries5Param,
              numberOfEntries6: numberOfEntries6Param,
              winRate121: winRate121Param,
              winRate122: winRate122Param,
              winRate123: winRate123Param,
              winRate124: winRate124Param,
              winRate125: winRate125Param,
              winRate126: winRate126Param,
              startTime1: startTime1Param,
              startTime2: startTime2Param,
              startTime3: startTime3Param,
              startTime4: startTime4Param,
              startTime5: startTime5Param,
              startTime6: startTime6Param,
              firstPlace1: firstPlace1Param,
              firstPlace2: firstPlace2Param,
              firstPlace3: firstPlace3Param,
              firstPlace4: firstPlace4Param,
              firstPlace5: firstPlace5Param,
              firstPlace6: firstPlace6Param,
              secondPlace1: secondPlace1Param,
              secondPlace2: secondPlace2Param,
              secondPlace3: secondPlace3Param,
              secondPlace4: secondPlace4Param,
              secondPlace5: secondPlace5Param,
              secondPlace6: secondPlace6Param,
              thirdPlace1: thirdPlace1Param,
              thirdPlace2: thirdPlace2Param,
              thirdPlace3: thirdPlace3Param,
              thirdPlace4: thirdPlace4Param,
              thirdPlace5: thirdPlace5Param,
              thirdPlace6: thirdPlace6Param);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Member] entity fields to define ObjectBox queries.
class Member_ {
  /// See [Member.id].
  static final id =
      obx.QueryIntegerProperty<Member>(_entities[0].properties[0]);

  /// See [Member.dataTime].
  static final dataTime =
      obx.QueryStringProperty<Member>(_entities[0].properties[1]);

  /// See [Member.number].
  static final number =
      obx.QueryStringProperty<Member>(_entities[0].properties[2]);

  /// See [Member.name].
  static final name =
      obx.QueryStringProperty<Member>(_entities[0].properties[3]);

  /// See [Member.kana3].
  static final kana3 =
      obx.QueryStringProperty<Member>(_entities[0].properties[4]);

  /// See [Member.blanch].
  static final blanch =
      obx.QueryStringProperty<Member>(_entities[0].properties[5]);

  /// See [Member.rank].
  static final rank =
      obx.QueryStringProperty<Member>(_entities[0].properties[6]);

  /// See [Member.sex].
  static final sex =
      obx.QueryStringProperty<Member>(_entities[0].properties[7]);

  /// See [Member.age].
  static final age =
      obx.QueryStringProperty<Member>(_entities[0].properties[8]);

  /// See [Member.height].
  static final height =
      obx.QueryStringProperty<Member>(_entities[0].properties[9]);

  /// See [Member.weight].
  static final weight =
      obx.QueryStringProperty<Member>(_entities[0].properties[10]);

  /// See [Member.blood].
  static final blood =
      obx.QueryStringProperty<Member>(_entities[0].properties[11]);

  /// See [Member.winRate12].
  static final winRate12 =
      obx.QueryStringProperty<Member>(_entities[0].properties[12]);

  /// See [Member.rankPast1].
  static final rankPast1 =
      obx.QueryStringProperty<Member>(_entities[0].properties[13]);

  /// See [Member.rankPast2].
  static final rankPast2 =
      obx.QueryStringProperty<Member>(_entities[0].properties[14]);

  /// See [Member.rankPast3].
  static final rankPast3 =
      obx.QueryStringProperty<Member>(_entities[0].properties[15]);

  /// See [Member.birthplace].
  static final birthplace =
      obx.QueryStringProperty<Member>(_entities[0].properties[16]);

  /// See [Member.photo].
  static final photo =
      obx.QueryStringProperty<Member>(_entities[0].properties[17]);

  /// See [Member.kana].
  static final kana =
      obx.QueryStringProperty<Member>(_entities[0].properties[18]);

  /// See [Member.kana2].
  static final kana2 =
      obx.QueryStringProperty<Member>(_entities[0].properties[19]);

  /// See [Member.wBirthday].
  static final wBirthday =
      obx.QueryStringProperty<Member>(_entities[0].properties[20]);

  /// See [Member.gBirthday].
  static final gBirthday =
      obx.QueryStringProperty<Member>(_entities[0].properties[21]);

  /// See [Member.firstPlaceCount].
  static final firstPlaceCount =
      obx.QueryStringProperty<Member>(_entities[0].properties[22]);

  /// See [Member.secondPlaceCount].
  static final secondPlaceCount =
      obx.QueryStringProperty<Member>(_entities[0].properties[23]);

  /// See [Member.numberOfRace].
  static final numberOfRace =
      obx.QueryStringProperty<Member>(_entities[0].properties[24]);

  /// See [Member.numberOfFinals].
  static final numberOfFinals =
      obx.QueryStringProperty<Member>(_entities[0].properties[25]);

  /// See [Member.numberOfWins].
  static final numberOfWins =
      obx.QueryStringProperty<Member>(_entities[0].properties[26]);

  /// See [Member.startTiming].
  static final startTiming =
      obx.QueryStringProperty<Member>(_entities[0].properties[27]);

  /// See [Member.pastAbilityScore].
  static final pastAbilityScore =
      obx.QueryStringProperty<Member>(_entities[0].properties[28]);

  /// See [Member.lastAbilityScore].
  static final lastAbilityScore =
      obx.QueryStringProperty<Member>(_entities[0].properties[29]);

  /// See [Member.dataYear].
  static final dataYear =
      obx.QueryStringProperty<Member>(_entities[0].properties[30]);

  /// See [Member.dataSeason].
  static final dataSeason =
      obx.QueryStringProperty<Member>(_entities[0].properties[31]);

  /// See [Member.startDate].
  static final startDate =
      obx.QueryStringProperty<Member>(_entities[0].properties[32]);

  /// See [Member.endDate].
  static final endDate =
      obx.QueryStringProperty<Member>(_entities[0].properties[33]);

  /// See [Member.generation].
  static final generation =
      obx.QueryStringProperty<Member>(_entities[0].properties[34]);

  /// See [Member.nameKana].
  static final nameKana =
      obx.QueryStringProperty<Member>(_entities[0].properties[35]);

  /// See [Member.winPointRate].
  static final winPointRate =
      obx.QueryStringProperty<Member>(_entities[0].properties[36]);

  /// See [Member.numberOfEntries1].
  static final numberOfEntries1 =
      obx.QueryStringProperty<Member>(_entities[0].properties[37]);

  /// See [Member.numberOfEntries2].
  static final numberOfEntries2 =
      obx.QueryStringProperty<Member>(_entities[0].properties[38]);

  /// See [Member.numberOfEntries3].
  static final numberOfEntries3 =
      obx.QueryStringProperty<Member>(_entities[0].properties[39]);

  /// See [Member.numberOfEntries4].
  static final numberOfEntries4 =
      obx.QueryStringProperty<Member>(_entities[0].properties[40]);

  /// See [Member.numberOfEntries5].
  static final numberOfEntries5 =
      obx.QueryStringProperty<Member>(_entities[0].properties[41]);

  /// See [Member.numberOfEntries6].
  static final numberOfEntries6 =
      obx.QueryStringProperty<Member>(_entities[0].properties[42]);

  /// See [Member.winRate121].
  static final winRate121 =
      obx.QueryStringProperty<Member>(_entities[0].properties[43]);

  /// See [Member.winRate122].
  static final winRate122 =
      obx.QueryStringProperty<Member>(_entities[0].properties[44]);

  /// See [Member.winRate123].
  static final winRate123 =
      obx.QueryStringProperty<Member>(_entities[0].properties[45]);

  /// See [Member.winRate124].
  static final winRate124 =
      obx.QueryStringProperty<Member>(_entities[0].properties[46]);

  /// See [Member.winRate125].
  static final winRate125 =
      obx.QueryStringProperty<Member>(_entities[0].properties[47]);

  /// See [Member.winRate126].
  static final winRate126 =
      obx.QueryStringProperty<Member>(_entities[0].properties[48]);

  /// See [Member.startTime1].
  static final startTime1 =
      obx.QueryStringProperty<Member>(_entities[0].properties[49]);

  /// See [Member.startTime2].
  static final startTime2 =
      obx.QueryStringProperty<Member>(_entities[0].properties[50]);

  /// See [Member.startTime3].
  static final startTime3 =
      obx.QueryStringProperty<Member>(_entities[0].properties[51]);

  /// See [Member.startTime4].
  static final startTime4 =
      obx.QueryStringProperty<Member>(_entities[0].properties[52]);

  /// See [Member.startTime5].
  static final startTime5 =
      obx.QueryStringProperty<Member>(_entities[0].properties[53]);

  /// See [Member.startTime6].
  static final startTime6 =
      obx.QueryStringProperty<Member>(_entities[0].properties[54]);

  /// See [Member.firstPlace1].
  static final firstPlace1 =
      obx.QueryStringProperty<Member>(_entities[0].properties[55]);

  /// See [Member.firstPlace2].
  static final firstPlace2 =
      obx.QueryStringProperty<Member>(_entities[0].properties[56]);

  /// See [Member.firstPlace3].
  static final firstPlace3 =
      obx.QueryStringProperty<Member>(_entities[0].properties[57]);

  /// See [Member.firstPlace4].
  static final firstPlace4 =
      obx.QueryStringProperty<Member>(_entities[0].properties[58]);

  /// See [Member.firstPlace5].
  static final firstPlace5 =
      obx.QueryStringProperty<Member>(_entities[0].properties[59]);

  /// See [Member.firstPlace6].
  static final firstPlace6 =
      obx.QueryStringProperty<Member>(_entities[0].properties[60]);

  /// See [Member.secondPlace1].
  static final secondPlace1 =
      obx.QueryStringProperty<Member>(_entities[0].properties[61]);

  /// See [Member.secondPlace2].
  static final secondPlace2 =
      obx.QueryStringProperty<Member>(_entities[0].properties[62]);

  /// See [Member.secondPlace3].
  static final secondPlace3 =
      obx.QueryStringProperty<Member>(_entities[0].properties[63]);

  /// See [Member.secondPlace4].
  static final secondPlace4 =
      obx.QueryStringProperty<Member>(_entities[0].properties[64]);

  /// See [Member.secondPlace5].
  static final secondPlace5 =
      obx.QueryStringProperty<Member>(_entities[0].properties[65]);

  /// See [Member.secondPlace6].
  static final secondPlace6 =
      obx.QueryStringProperty<Member>(_entities[0].properties[66]);

  /// See [Member.thirdPlace1].
  static final thirdPlace1 =
      obx.QueryStringProperty<Member>(_entities[0].properties[67]);

  /// See [Member.thirdPlace2].
  static final thirdPlace2 =
      obx.QueryStringProperty<Member>(_entities[0].properties[68]);

  /// See [Member.thirdPlace3].
  static final thirdPlace3 =
      obx.QueryStringProperty<Member>(_entities[0].properties[69]);

  /// See [Member.thirdPlace4].
  static final thirdPlace4 =
      obx.QueryStringProperty<Member>(_entities[0].properties[70]);

  /// See [Member.thirdPlace5].
  static final thirdPlace5 =
      obx.QueryStringProperty<Member>(_entities[0].properties[71]);

  /// See [Member.thirdPlace6].
  static final thirdPlace6 =
      obx.QueryStringProperty<Member>(_entities[0].properties[72]);
}
